services:
  tei-embed:
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  tei-rerank:
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  tei-code-embed:
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
